# Generated by Django 5.2.6 on 2025-09-08 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_newuser_is_active_alter_newuser_is_staff_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newuser",
            old_name="user_name",
            new_name="username",
        ),
    ]
