# Generated by Django 5.2.6 on 2025-09-07 14:10

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=blog.models.upload_to
            ),
        ),
    ]
